# NBA Stats Tracker Configuration

[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "your-email@gmail.com"
sender_password = "your-app-password"
notification_email = "your-notification-email@example.com"

[database]
path = "data/nba_stats.db"
backup_enabled = true
backup_interval_days = 7

[thresholds]
# Statistical thresholds for notifications
[thresholds.points_per_game]
min = 20.0
max = 35.0

[thresholds.assists_per_game]
min = 6.0
max = 12.0

[thresholds.rebounds_per_game]
min = 8.0
max = 15.0

[thresholds.steals_per_game]
min = 1.5
max = 3.0

[thresholds.blocks_per_game]
min = 1.8
max = 3.5

[mvp_analysis]
# Minimum categories a player must lead to be considered MVP candidate
min_categories = 2
# Whether to consider historical performance
include_historical = true
historical_days = 30

[scraping]
# Scraping schedule in cron format
schedule = "0 11 * * *"  # 11 AM EST daily
retry_attempts = 3
retry_delay_seconds = 300  # 5 minutes

[selenium]
headless = true
timeout_seconds = 30
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

[logging]
level = "INFO"
file_path = "logs/nba_stats.log"
max_size_mb = 100
backup_count = 5
