# Template for sensitive configuration - Copy this file to secrets.toml and fill in your values
[email]
sender_email = "your-email@gmail.com"
sender_password = "your-app-password"
notification_email = "your-notification-email@example.com"
